name: animated_responsive_layout
description: Therapistdog

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  extension_google_sign_in_as_googleapis_auth: ^2.0.9
  flex_color_scheme: ^7.0.1
  flutter:
    sdk: flutter
  go_router: ^6.5.5
  googleapis: ^10.1.0
  googleapis_auth: ^1.4.0
  http: ^0.13.5
  provider: ^6.0.5
  split_view: ^3.2.1
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/avatar_1.png
    - assets/avatar_2.png
    - assets/avatar_3.png
    - assets/avatar_4.png
    - assets/avatar_5.png
    - assets/avatar_6.png
    - assets/avatar_7.png
    - assets/thumbnail_1.png